name: netease_music_api
description: Netease cloud music api for flutter ,reference https://github.com/Binaryify/NeteaseCloudMusicApi.
version: 0.0.1
author: hcanyz
homepage: https://github.com/hcanyz/flutter-netease-music-api

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # app path
  path_provider: ^1.6.8

  # http
  dio: 3.0.9
  pretty_dio_logger: ^1.1.1
  dio_cookie_manager: ^1.0.0

  # encrypt
  encrypt: ^4.0.0
  pointycastle: ^1.0.2

  # x json
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # x json
  build_runner: ^1.9.0
  json_serializable: ^3.3.0

  # mock
  mockito: ^4.1.1